server.port: ${SERVER_PORT:0}

spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  application:
    name: stats-server

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_stats_db
    username: postgres
    password: password

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER_URL:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
    instance-id: "${spring.application.name}:${random.value}"

logging.level:
  ru.practicum: INFO
  org.springframework.jdbc.datasource.init: DEBUG