server.port: 9090

spring:
  sql.init.mode: always
  output.ansi.enabled: ALWAYS

  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/ewm_stats_db
    username: postgres
    password: password

logging.level:
  ru.practicum: INFO
  org.springframework.jdbc.datasource.init: DEBUG