server.port: 8080

logging:
  file:
    name: logs/${spring.application.name}.log
  level:
    org.springframework.cloud.gateway: TRACE

spring:
  output.ansi.enabled: ALWAYS
  cloud:
    gateway:
      server:
        webflux:
          routes:
            # ----- User service -----
            - id: user-service-route
              uri: lb://user
              predicates:
                  - Path=/admin/users/**

            # ----- Participation service -----
            - id: participation-service-user-route
              uri: lb://participation
              predicates:
                - Path=/users/{userId}/requests/**

            # ----- Main service -----
            - id: main-service-route
              uri: lb://main-service
              predicates:
                - Path=/**
