server:
  port: 8080

stats:
  server:
    url: http://localhost:9090


spring:
  output.ansi.enabled: ALWAYS # цветной вывод в консоль
  sql.init.mode: always

  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ewm_main_db}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:password}
  jpa:
    show-sql: true
    "properties.hibernate.format_sql": true
    hibernate:
      ddl-auto: none
  jackson:
    "serialization.write-dates-as-timestamps": false

logging:
  level:
    "org.zalando.logbook": TRACE
    "org.springframework.orm.jpa": INFO
    "org.springframework.orm.jpa.JpaTransactionManager": DEBUG
    "org.springframework.transaction": INFO
    "org.springframework.transaction.interceptor": TRACE
    org.springframework.jdbc.datasource.init: DEBUG